  /* This file generated by /data/data/com.termux/files/home/datlas/thread/../ATLAS//tune/threads/probe_nthr.c */
#ifndef ATLAS_NTHREADS_H
   #define ATLAS_NTHREADS_H

#include "pthread.h"
/*
 * I should have tested if NTHREADS = 0(NCPU) or 10(NAFFIDs)
 * is better.  For now, assuming 4
 */   #define ATL_NTHREADS 4
   #define ATL_NTHRPOW2 2
   #ifdef ATL_LAUNCHORDER
       static int ATL_launchorder[4] = {0,2,1,3};
   #endif

#endif
