/* Generated by /data/data/com.termux/files/home/datlas/thread/../ATLAS//CONFIG/src/probe_aff.c */
#ifndef ATL_TAFFINITY_H
   #define ATL_TAFFINITY_H

#define _GNU_SOURCE 1 /* what manpage says you need to get CPU_SET */
#define __USE_GNU   1 /* what actually works on linuxes I've seen */
#include <sched.h>    /* must be included with above defs before pthread.h */

#define ATL_HAS_AFFINITY 6
#define ATL_PAFF_SCHED 1
#define ATL_PAFF_SELF 1  /* affinity must be set by thr after launched */
#define ATL_AFF_NUMID 4
#define ATL_AFF_IDSTRIDE 1
#define ATL_RANK_IS_PROCESSORID 1 /* good IDs [0,3] */

#endif /* end multiple inclusion guard */
